brew "git-lfs"
brew "cmake"
brew "java"

cask "zoom"
cask "slack"
cask "github"
cask "visual-studio-code"
cask "docker"
cask "wireshark"
cask "mongodb-compass"
cask "sf-symbols"
cask "ltspice"
cask "telegram"
cask "whatsapp"
cask "spotify"
cask "google-chrome"